set nocompatible
set modelines=0
set autochdir
set backspace=2
set tabstop=4
set autoindent
set shiftwidth=4
set number
set mouse=a
set ruler
set showmatch
set selection=exclusive
set selectmode=mouse,key
set laststatus=2
syntax on
source $VIMRUNTIME/mswin.vim
behave mswin